### ISSUE TITLE
Can I help?

### ISSUE THREAD

**Issue by cchubb** [BIOSTALL/CodeIgniter-Google-Maps-V3-API-Library#1]
I'm loving your CI library but I have some stuff I want to add to it. If I fork it, are you open to rolling my mods back into the core? (If not, no biggie, but I probably won't go through all of the trouble in that case...)

**Comment by BIOSTALL** [comment]
Hey Chris,

Thanks for getting in touch and for the kind words ref the library. What 
you propose sounds great and I'd give credit where it's due. What kind 
of things did you have in mind :)

Cheers,

Steve

**Comment by cchubb** [comment]
I'm going to optimize the caching of the geocoding db lookup as well as providing a javascript callback to decorate the Places marker windows. I'm also looking at how to modify the places search so that if the viewpane is shifted it will requery within the new boundaries. Think others would want that functionality?
