### ISSUE TITLE
https://developers.google.com/maps/documentation/javascript/reference#InfoWindowOptions

### ISSUE THREAD

**Issue by vincent3569** [BIOSTALL/CodeIgniter-Google-Maps-V3-API-Library#10]
hi

the google.maps.InfoWindow class supports an interesting option : maxWidth (Maximum width of the infowindow, regardless of content's width).

https://developers.google.com/maps/documentation/javascript/reference#InfoWindowOptions

could you add an option s on markers to allow this option ?

**Comment by BIOSTALL** [comment]
This is now available as an option when initalising the map. See:

69764ec1a4e5f0c9939ab2675f7caddd3c31e74b
