### ISSUE TITLE
what if the requests more than 2500?

### ISSUE THREAD

**Issue by ghost** [BIOSTALL/CodeIgniter-Google-Maps-V3-API-Library#11]
Hai BIOSTALL,

Here I have a question for you that is in the document I saw that the the requests was limited to 2500. What if the requests more than 2500?

And I have one more doubt
Is there any requirment to get API key.?
Can I use your library in my website to show the map of user entered location.

Thank you very much.

**Comment by BIOSTALL** [comment]
Hi Madhu,

I've just made an update to the library that now allows you to pass in an API key.

Thanks
