### ISSUE TITLE
How do you use geolocation to retrive nearest results?

### ISSUE THREAD

**Issue by simonda86** [BIOSTALL/CodeIgniter-Google-Maps-V3-API-Library#15]
I've been looking at the geolocation example (http://biostall.com/demos/google-maps-v3-api-codeigniter-library/geolocation) and this works fine for the centering the map at the users location. But what if I wanted to show the 10 nearest results from a database? Is there a way to acces the lng and lat from geolocation?

**Comment by jedwan** [comment]
Did you ever get a solution for this?

**Comment by simonda86** [comment]
Hi Jedwan,

I ended up using https://github.com/estebanav/javascript-mobile-desktop-geolocation on a page and then when I've got the coords redirecting to another page passing parameters such as: 

``` JavaScript
'?lat=' + position.coords.latitude + '&lng=' + position.coords.longitude;
```

Which worked fine for me.
