### ISSUE TITLE
How to add own places and show them in the google maps on my CI page?

### ISSUE THREAD

**Issue by keessonnema** [BIOSTALL/CodeIgniter-Google-Maps-V3-API-Library#16]
Hello,

I just started using Google Maps Api Library for Codeigniter.
i'm working on an application where people can search based on their postal code and a radius.
i was wondering how to do this with the google maps api. when i turn on Places in my controller i get the nearest places from the lat/lng code. but i want to have a database with postalcodes and an 'own' place. form where the people can search. this is based on their postcode and a radius of about 20km.

Hope someone could help me out with this.

**Comment by simonda86** [comment]
Hello Keessonnema,

You'll need the places to be stored in the database with lat and lng and then use the Haversine formula to do the search. Have a look at:

http://en.wikipedia.org/wiki/Haversine_formula
and 
https://gist.github.com/adrienne/3180103

Hope that helps,

Simon

**Comment by keessonnema** [comment]
Hey Simon,

I will look at this. thanks for your answer :)

Kees
