### ISSUE TITLE
Problem fix Uncaught Error: NotFoundError: DOM Exception 8

### ISSUE THREAD

**Issue by chiqui3d** [BIOSTALL/CodeIgniter-Google-Maps-V3-API-Library#17]
Hello
change
window.onload = initialize;
for
google.maps.event.addDomListener(window, "load", initialize);

**Comment by BIOSTALL** [comment]
Thanks for your suggestion. This has now been actioned:

116a15e45c7ea78e00b3eaf4dd24aace56a5976e
