### ISSUE TITLE
Custom MULTIPLE Markers to toggle on Map

### ISSUE THREAD

**Issue by Matrix1990** [BIOSTALL/CodeIgniter-Google-Maps-V3-API-Library#19]
I am using your library for a website which is fantastic. After reading your documentation i am still a little confused on how to create multiple icon markers to integrate into the library.

In the library file i can see where to add the custom marker: $marker['icon'] = ''; but in my database where my information is stored i have a field name called type and either say 'bars' and 'restaurants' for example. I am after to assign each type a custom marker and display on the map, which users are then able to toggle using buttons.

The marker type is brought in as follows:

$marker = array('id'=> $coordinate->type ---other elements---);

Is this possible to do using your library?

Thanks!

**Comment by Matrix1990** [comment]
Easily sorted with this in the contoller:

if($coordinate->type == "restaurant"){
                $image = 'http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=A|FF0000|000000';
            }

and so on.

**Comment by BIOSTALL** [comment]
Hi Matrix. Glad you found the solution. For other in a similar situation I've included a more extensive example below to clarify things:

``` php
$marker = array();
$marker['position'] = 'My Address, My Town';
switch ($coordinate->type)
{
    case "restaurant": {
        $image = 'http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=A|FF0000|000000';
        break;
    }
    case "bar": {
        $image = 'http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=B|FF0000|000000';
        break;
    }
    // Enter other types here and assign them each to an icon
}
$marker['icon'] = $image;
$this->googlemaps->add_marker($marker);
```
