### ISSUE TITLE
Still requesting geocode of location to Google although geocodecaching is turned on

### ISSUE THREAD

**Issue by pascalspruit** [BIOSTALL/CodeIgniter-Google-Maps-V3-API-Library#24]
Although in 99% of the cases I'm requesting the same locations and having geocodecaching turned on, I'm still exceeding Googles daily limit very rapidly.

Looking at the function get_lat_long_from_address() it seems like, while geocodecaching is turned on, an address is still send to Google for geocoding even though a record already exists in the geocoding table. Shouldn't this be changed so that this is only done in case no records are returned ($query->num_rows()==0).

**Comment by BIOSTALL** [comment]
Hi pascalspruit, 

I have taken a look at your issue and can confirm that it doesn't perform a geocode request if it finds a result in the cache.

On line 2162 of the current file it reads as follows:

`if ($query->num_rows()>0) {
    $row = $query->row();
    return array($row->latitude, $row->longitude);
}`

Note how it's returning if it finds a row. If you're still experiencing problems can you confirm that: he row definitely exists in the 'geocoding' table?

Hope that helps.
Steve
