### ISSUE TITLE
can i use your library for another framework such as laravel ?

### ISSUE THREAD

**Issue by navotera** [BIOSTALL/CodeIgniter-Google-Maps-V3-API-Library#25]
hi... i used to be using your library in the CI framework, but i eager to learn new framework laravel. as far i know your library is very easy to use but i cannot find same as yours for laravel package (library).

i want to know is this library framework independent or can i use it with another framework ? 

thanks bro... :)

**Comment by michaeljhopkins** [comment]
For whatever its worth if you're still looking for this I've converted this library into a composer package that can be used with laravel

**Comment by BIOSTALL** [comment]
Hi Michael, This is great news and something I get asked about a lot. I've seen your github repo and will link to it later to assist others. Good job :)

**Comment by michaeljhopkins** [comment]
It looks like I had a noreadme version on my personal github. This one properly attributes where the code came from
https://github.com/appitventures/Phpgmaps
