### ISSUE TITLE
Adding Distance scale

### ISSUE THREAD

**Issue by maan81** [BIOSTALL/CodeIgniter-Google-Maps-V3-API-Library#29]
Is there a way that I could display the distance scale - in KM or Miles or anything reasonable - as it is shown in http://maps.google.com ?

**Comment by BIOSTALL** [comment]
There is now. The option did exist but was bugged. I've just put a fix in (1033b71afd64a7bcf3cd678729ed680563c624e7) to resolve this.

You just need to set the 'scaleControlPosition' configuration option when loading the map. ie.

```
$config['scaleControlPosition'] = 'BOTTOM_RIGHT';
$this->googlemaps->initialize($config);
```
