### ISSUE TITLE
Cluster by https

### ISSUE THREAD

**Issue by cristoj** [BIOSTALL/CodeIgniter-Google-Maps-V3-API-Library#30]
Cluster doesn't work if the page is https, when this library load the script cluster: 

```
<script>http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/src/markerclusterer_compiled.js</script>
```

, it is necesary check if https or not in order to pass this variable to the previous code

**Comment by BIOSTALL** [comment]
Thanks. This has now been fixed. See below commit:

1237709958d54c22cd16f951b88a59acbcded726
