### ISSUE TITLE
Oops! Something went wrong. This page didn't load Google Maps correctly. See the JavaScript console

### ISSUE THREAD

**Issue by arufango** [BIOSTALL/CodeIgniter-Google-Maps-V3-API-Library#51]
on my map show word "Oops! Something went wrong. This page didn't load Google Maps correctly. See the JavaScript console"
how to fix it?

**Comment by arufango** [comment]
ooh, now fix.
just add apikey.

**Comment by ofin** [comment]
i have that same problem. how do you resolve that?

**Comment by fabriciocruz** [comment]
Do you applied apikey in the file libraries/Googlemaps.php?

**Comment by arufango** [comment]
Just add your apikey in file libraries/Googlemaps.php
put it on **var $apiKey	= '_your apikey_';**

**Comment by BIOSTALL** [comment]
You don't need to hack the main library. Pass it through when init'ing the map:

```
$config['center'] = '37.4419, -122.1419';
$config['zoom'] = 'auto';
$config['apiKey'] = 'XXXXXX';
$this->googlemaps->initialize($config);
```
