### ISSUE TITLE
Methods with the same name as their class will not be constructors.

### ISSUE THREAD

**Issue by bhavsardhruv** [BIOSTALL/CodeIgniter-Google-Maps-V3-API-Library#59]
Methods with the same name as their class will not be constructors in a future version of PHP; Googlemaps has a deprecated constructor

Filename: libraries/Googlemaps.php

Line Number: 17

**Comment by Tpojka** [comment]
> Warning
Old style constructors are DEPRECATED in PHP 7.0, and will be removed in a future version. You should always use __construct() in new code. 

Try changing library code to `__construct()` instead of `googlemaps()`.

[Docs.](http://php.net/manual/en/language.oop5.decon.php)

**Comment by bhavsardhruv** [comment]
Thank you so much
