### ISSUE TITLE
getting marker new position on ondragend event

### ISSUE THREAD

**Issue by Hretic** [BIOSTALL/CodeIgniter-Google-Maps-V3-API-Library#6]
hi
i want to update position in the database when someone is dragging the marker .
i think i have to send a ajax request on "ondragend" event and send the new position to my CI controller .

but how can i get the new position on "ondragend" event ? 

$this->load->library('googlemaps');
$this->googlemaps->initialize($config);
$marker = array();
$marker['draggable'] = true ;
$marker['ondragend'] = "UpdatePosition(lt , lg )" ;
$this->googlemaps->add_marker($marker);
$data['map'] = $this->googlemaps->create_map(); 

lt and lg are latitude and longitude coordinates

$marker['ondragend'] = "UpdatePosition(lt , lg )" ;

**Comment by BIOSTALL** [comment]
Hi maxxxir,

Thanks for your question. Please see the demo at the URL below:

http://biostall.com/demos/google-maps-v3-api-codeigniter-library/dragmarker

This demonstrates getting the markers position when dragging has completed.

Please note, you may need to download the latest version of the library as this functionality was added in one of the most recent commits.

Give me a shout if any more guidance required.

Good luck!

Steve

**Comment by adlahd** [comment]
Hello, can i pass the lat & long from view to controller directly ?
