### ISSUE TITLE
no infowindows if loadAsynchronously=true

### ISSUE THREAD

**Issue by vincent3569** [BIOSTALL/CodeIgniter-Google-Maps-V3-API-Library#9]
hi

when I have this config : $config['loadAsynchronously'] = false;

infowindows on markers are never shown even after a click on it.

**Comment by BIOSTALL** [comment]
This has now been fixed in commits:

52ad1717401ee76d890567ab7af5e1c1d6b53bae
c708b58df688d351be75654865d837bf4752977c
